### ISSUE TITLE
Error for any query since today, 2018-04-01

### ISSUE THREAD

**Issue by ToBeFree** [enterprisey/afdstats#1]
If this has not been caused by any software modification of adfstats, then something has changed on the Toolserver, maybe.

```
Traceback (most recent call last): File "/data/project/afdstats/public_html//afdstats.py", line 91, in main db = MySQLdb.connect(db='enwiki_p', host="enwiki.labsdb", read_default_file=os.path.expanduser("~/replica.my.cnf")) File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect return Connection(*args, **kwargs) File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__ super(Connection, self).__init__(*args, **kwargs2) OperationalError: (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 0") None

Fatal error.
```

Example queries:

https://tools.wmflabs.org/afdstats/afdstats.py?name=ToBeFree&max=&startdate=&altname=
https://tools.wmflabs.org/afdstats/afdstats.py?name=ToBeFree&max=500&startdate=&altname=
https://tools.wmflabs.org/afdstats/afdstats.py?name=Sergecross73&max=500&startdate=&altname=

**Comment by ToBeFree** [comment]
Hm. Solved. Might have been some temporary issue.
